# Generated by Django 3.0.7 on 2020-06-05 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('colors', models.CharField(choices=[('BLK', 'black'), ('WHE', 'white'), ('GRY', 'grey'), ('BRW', 'brown'), ('RED', 'red'), ('GRN', 'green'), ('YLW', 'yellow'), ('BLE', 'blue'), ('PRP', 'purple')], default='GRY', max_length=3)),
                ('life', models.IntegerField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='fish/', verbose_name='Photo')),
                ('eating', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
